"""Nifty 100 Analytics — Streamlit entry point (Sprint 4).

Sidebar navigation to all 8 screens is auto-generated by Streamlit's
native multipage support from the `pages/` directory:
  01_home.py, 02_profile.py, 03_screener.py, 04_peers.py,
  05_trends.py, 06_sectors.py, 07_capital.py, 08_reports.py
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import streamlit as st

st.set_page_config(layout="wide", page_title="Nifty 100 Analytics", initial_sidebar_state="expanded")

st.title("Nifty 100 Analytics")
st.caption("Financial intelligence for India's top listed companies")

st.markdown(
    """
    Use the **sidebar** to navigate the 8 screens:

    | Screen | What you'll find |
    |---|---|
    | 01 Home | Market-wide KPIs, sector donut, top-5 by composite score |
    | 02 Profile | Single-company deep dive: KPIs, 10-year trends, pros & cons |
    | 03 Screener | 6 investment presets + custom threshold filters, CSV export |
    | 04 Peers | Peer-group percentile rankings and radar comparison |
    | 05 Trends | 10-year metric trends with YoY annotations |
    | 06 Sectors | Sector bubble chart and median KPI comparison |
    | 07 Capital | Capital-allocation treemap across 8 patterns |
    | 08 Reports | Annual-report PDF links per company |
    """
)
